spring:
  application:
    name: gymrat

  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gymrat
    username: gymrat
    password: gymrat
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      jakarta:
        persistence:
          # SCHEMA GENERATION
          schema-generation:
            scripts:
              action: create
              create-target: schema.sql
  # ACTUATOR
  management:
    endpoints:
      web:
        base-path: /management
        exposure:
          include: [ "health" ]

# DOCS:
springdoc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# LOG LEVELS
logging:
  level:
    ROOT: INFO
    n1b3lung0: DEBUG
    web: DEBUG

# SERVICE DISCOVERY
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: gymrat
server:
  port: ${PORT:0}
